name: Montgomery Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"  # daily at noon UTC

jobs:
  scrape:
    runs-on: ubuntu-latest
    container:
      image: selenium/standalone-chrome:latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        run: |
          apt-get update && apt-get install -y python3 python3-pip
          python3 -m pip install -r requirements.txt

      - name: Run Scraper
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
        run: |
          python3 main.py