name: Montgomery Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: "10 13 * * *"  # daily at noon UTC

jobs:
  scrape:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        env:
          SE_NODE_SESSION_TIMEOUT: 60
        ports:
          - 4444:4444
        options: >-
          --shm-size="2g"

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          pip3 install -r requirements.txt

      - name: Run Scraper
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
        run: |
          export SELENIUM_REMOTE_URL="http://localhost:4444/wd/hub"
          python3 main.py