name: Montgomery County Scraper

on:
  schedule:
    - cron: '10 13 * * *'  # Run daily at 2 AM UTC
  workflow_dispatch:  # Allow manual triggering

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium gspread google-auth
        
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-chromedriver
        
    - name: Run scraper
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
      run: |
        python montgomery_scraper.py
        
    - name: Notify on failure
      if: failure()
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: 'Montgomery County Scraper Failed',
            body: 'The scheduled Montgomery County scraper run failed. Please check the logs.'
          })