name: Montgomery County Scraper

on:
  schedule:
    - cron: '10 13 * * *'  # Run daily at 2 AM UTC
  workflow_dispatch:  # Allow manual triggering

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-chromedriver

    - name: Run scraper
      env:
        # Correctly pass the multiline JSON secret as a single line
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS | toJSON }}
        SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
      run: python main.py

    - name: Upload logs on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: montgomery-scraper-logs
        path: scraper.log # Updated log file name

    - name: Notify on failure
      if: failure()
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: "Montgomery County Scraper Failed",
            body: "The Montgomery County scraper workflow failed. Please check the logs."
          })